### ISSUE TITLE
CSV/JSON/etc classes?

### ISSUE THREAD

**Issue by rolodato** [heuermh/lick#4]
Hi @heuermh, LicK looks great. I've recently started diving into ChucK and found the need to read structured data from external files, but couldn't find a way and [ended up doing something like this](https://github.com/rolodato/cc-to-nrpn/blob/4756c59ada0712b38b5e8000cd363b826ad617f6/scripts/mopho.ck#L31-L80).

Do you know if there's a way to read from a CSV, JSON or other structured format using LicK or straight ChucK? If not, let me know and I can contribute a reader if this is something people could find useful. Thanks!

**Comment by heuermh** [comment]
File I/O in ChucK is not so great generally, so often I use Processing or Java to do parsing and then communicate with ChucK via MIDI or OSC.

That said, some library code to read structured formats, especially relevant things like MIDI mappings, [drum machine patterns](http://www.ethanhein.com/wp/2010/drum-machine-programming/), [musical scales](http://www.huygens-fokker.org/scala/scl_format.html), [muscial notation](https://en.wikipedia.org/wiki/ABC_notation), etc. would certainly be welcome here!

Some simple I/O examples here
http://chuck.cs.princeton.edu/doc/examples/io/

I thought there was a ChucK `StringTokenizer` but now I can't find mention of it.

**Comment by heuermh** [comment]
Closing issue as WontFix.  If you come up with any reader implementations and want to contribute them to LiCK, please create a pull request!
