### ISSUE TITLE
Add relative path in import.ck

### ISSUE THREAD

**Issue by 01010101** [heuermh/lick#8]
Would be nice to modify import.ck to use a relative path when adding the library's ck files so import.ck can be called from anywhere.

// Get import.ck path
me.dir() => string path;

// functional interfaces or functors, package fn
Machine.add(path+"/lick/fn/BinaryFunction.ck");

**Comment by heuermh** [comment]
Thanks for the suggestion, @01010101!

When I run stuff with LiCK I'm running from the `lick` source directory and
```
$ chuck --loop &
```
in one terminal window and
```
$ chuck + import.ck
$ chuck + examples/foo.ck
```
in another.  What is your use case, and how might this help?

**Comment by 01010101** [comment]
Hi.
I also run chuck this way (tmux or screen window) but was thinking it would be useful to have some kind of utils or libs (incl. lick) in an external folder. 
This way I can refer to some of them from any working directory so I don't have to copy/duplicate those files nor have everything I'm working on at the same place, or even navigate directories.
It just seemed more natural to me to do imports this way. 

But, indeed, I can do the opposite and run chuck from that lib/utils folder, then manage paths within my ck files.

**Comment by heuermh** [comment]
Thanks, let's talk that through.  You have
```
lick/import.ck
lick/lick/...
working/foo.ck
```

and you'd like to do
```
$ pwd
working

$ chuck --loop &
$ chuck + foo.ck
```

foo.ck:
```
Machine.add("../lick/import.ck");
<<<"ok">>>;
```

or perhaps
```
$ chuck --loop &
$ chuck + ../lick/import.ck foo.ck
```
?

**Comment by 01010101** [comment]
Yeah, that's the idea
